Update pmwf
This is a major update. Ditched Perl & Curl and pmwf now uses built-in utilities that ship with almost all Linux distributions. Also improved the dependency and error handling mechanism. pmwf is now more robust and reliable than ever before. Enjoy!

diff --git a/pmwf b/pmwf
--- a/pmwf
+++ b/pmwf
@@ -1,95 +1,165 @@
-#!/bin/bash
+#!/usr/bin/env bash
+########################################
+local_latitude=
+local_longitude=
+local_unit=
+api_key=
+local_rm=$(which rm)
+########################################
 
-export LC_TIME=C
-export LC_ALL=C
+printf "\033c"
 
-clear
+if [ -z "$local_latitude" ]; then
+	echo ""
+	echo "Variable \"local_latitude\" is either unset or empty!"
+	echo ""
+	exit 1
+fi
 
-latit=
-longi=
-uneet=
-apkey=
+if [ -z "$local_longitude" ]; then
+	echo ""
+	echo "Variable \"local_longitude\" is either unset or empty!"
+	echo ""
+	exit 1
+fi
 
-curl -s --connect-timeout 30 -o /tmp/current.json "http://api.openweathermap.org/data/2.5/weather?lat=$latit&lon=$longi&units=$uneet&mode=json&APPID=$apkey"
-curl -s --connect-timeout 30 -o /tmp/forecast.json "http://api.openweathermap.org/data/2.5/forecast/daily?lat=$latit&lon=$longi&cnt=4&units=$uneet&mode=json&APPID=$apkey"
+if [ -z "$local_unit" ]; then
+	echo ""
+	echo "Variable \"local_unit\" is either unset or empty!"
+	echo ""
+	exit 1
+fi
 
-if [ ! -f /tmp/forecast.json ]; then
-echo ""
-echo -e "Unable to connect to openweathermap.org!"
-echo -e "Check your internet connection!"
-echo ""
+if [ -z "$api_key" ]; then
+	echo ""
+	echo "Variable \"api_key\" is either unset or empty!"
+	echo ""
+	exit 1
+fi
 
-exit 1
+type wget >/dev/null 2>&1 || { printf "\033c"; echo -e ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo -e ""; echo -e '\e[38;5;82m'"A required pmwf dependency \"Wget\" is unavailable"; echo -e '\e[38;5;82m'"\"Wget\" is available for almost all linux distros."; echo -e '\e[38;5;82m'"Please install \"wget\" using your package manager."; echo -e '\e[38;5;82m'"Please visit the homepage of \"Wget\" for more info"; echo -e '\e[38;5;82m'"https://www.gnu.org/software/wget/"; echo -e ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo -e ""; tput sgr0; exit 1; }
 
-else
-place=$(cat /tmp/forecast.json | jq -r '.city.name')
-nation=$(cat /tmp/forecast.json | jq -r '.city.country')
-time2=$(cat /tmp/forecast.json | jq -r '.list[1].dt')
-time3=$(cat /tmp/forecast.json | jq -r '.list[2].dt')
-time4=$(cat /tmp/forecast.json | jq -r '.list[3].dt')
+
+type jq >/dev/null 2>&1 || { printf "\033c"; echo -e ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo -e ""; echo -e '\e[38;5;82m'"A required pmwf dependency \"jq\" is unavailable"; echo -e '\e[38;5;82m'"\"jq\" is available for almost all linux distros."; echo -e '\e[38;5;82m'"Please install \"jq\" using your package manager."; echo -e '\e[38;5;82m'"Please visit the homepage of \"jq\" for more info"; echo -e '\e[38;5;82m'"https://jqlang.github.io/jq/"; echo -e ""; for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; echo -e ""; tput sgr0; exit 1; }
+
+if ! wget --spider --user-agent="Mozilla/5.0 Gecko/20100101" --no-check-certificate --quiet --timeout=30 -q "www.google.com" -O /dev/null; then
+	printf "\033c"
+	echo ""
+	{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
+	echo ""
+	echo -e '\e[38;5;82m' "No active internet connection available!!"
+	echo -e '\e[38;5;82m' "Please check your internet connectivity!!"
+	echo ""
+	{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
+	echo ""
+	tput sgr0
+	exit 1
+fi
+
+wget --user-agent="Mozilla/5.0 Gecko/20100101" --quiet --timeout=30 "http://api.openweathermap.org/data/2.5/weather?lat=$local_latitude&lon=$local_longitude&units=$local_unit&mode=json&APPID=$api_key" --output-document "/tmp/current.json"
+
+wget --user-agent="Mozilla/5.0 Gecko/20100101" --quiet --timeout=30 "http://api.openweathermap.org/data/2.5/forecast/daily?lat=$local_latitude&lon=$local_longitude&cnt=4&units=$local_unit&mode=json&APPID=$api_key" --output-document "/tmp/forecast.json"
+
+if [[ ! -f "/tmp/current.json" ]]; then
+	echo ""
+	echo -e "Failed to get the weather data from openweathermap.org!"
+	echo -e "Make sure that you are able to connect to this website!"
+	echo ""
+	exit 1
+fi
+
+if [[ ! -f "/tmp/forecast.json" ]]; then
+	echo ""
+	echo -e "Failed to get the weather data from openweathermap.org!"
+	echo -e "Make sure that you are able to connect to this website!"
+	echo ""
+	exit 1
+fi
+
+if ! grep -q '[^[:space:]]' "/tmp/current.json"; then
+	echo ""
+	echo -e "Failed to get the weather data from openweathermap.org!"
+	echo -e "Make sure that you are using a valid and active API key!"
+	echo ""
+	exit 1
+fi
+
+if ! grep -q '[^[:space:]]' "/tmp/forecast.json"; then
+	echo ""
+	echo -e "Failed to get the weather data from openweathermap.org!"
+	echo -e "Make sure that you are using a valid and active API key!"
+	echo ""
+	exit 1
+fi
+
+place=$(jq -r '.city.name' "/tmp/forecast.json")
+nation=$(jq -r '.city.country' "/tmp/forecast.json")
+time2=$(jq -r '.list[1].dt' "/tmp/forecast.json")
+time3=$(jq -r '.list[2].dt' "/tmp/forecast.json")
+time4=$(jq -r '.list[3].dt' "/tmp/forecast.json")
 time22=$(date -d @"$time2" +'%A, %d %B %Y')
 time33=$(date -d @"$time3" +'%A, %d %B %Y')
 time44=$(date -d @"$time4" +'%A, %d %B %Y')
-tempcurrent=$(cat /tmp/current.json | jq -r '.main.temp')
-min2=$(cat /tmp/forecast.json | jq -r '.list[1].temp.min')
-min3=$(cat /tmp/forecast.json | jq -r '.list[2].temp.min')
-min4=$(cat /tmp/forecast.json | jq -r '.list[3].temp.min')
-max2=$(cat /tmp/forecast.json | jq -r '.list[1].temp.max')
-max3=$(cat /tmp/forecast.json | jq -r '.list[2].temp.max')
-max4=$(cat /tmp/forecast.json | jq -r '.list[3].temp.max')
-pressurecurrent=$(cat /tmp/current.json | jq -r '.main.pressure')
-pressure2=$(cat /tmp/forecast.json | jq -r '.list[1].pressure')
-pressure3=$(cat /tmp/forecast.json | jq -r '.list[2].pressure')
-pressure4=$(cat /tmp/forecast.json | jq -r '.list[3].pressure')
-humidcurrent=$(cat /tmp/current.json | jq -r '.main.humidity')
-humid2=$(cat /tmp/forecast.json | jq -r '.list[1].humidity')
-humid3=$(cat /tmp/forecast.json | jq -r '.list[2].humidity')
-humid4=$(cat /tmp/forecast.json | jq -r '.list[3].humidity')
-windcurrent=$(cat /tmp/current.json | jq -r '.wind.speed')
-wind2=$(cat /tmp/forecast.json | jq -r '.list[1].speed')
-wind3=$(cat /tmp/forecast.json | jq -r '.list[2].speed')
-wind4=$(cat /tmp/forecast.json | jq -r '.list[3].speed')
-direcurrent=$(cat /tmp/current.json | jq -r '.wind.deg')
-dire2=$(cat /tmp/forecast.json | jq -r '.list[1].deg')
-dire3=$(cat /tmp/forecast.json | jq -r '.list[2].deg')
-dire4=$(cat /tmp/forecast.json | jq -r '.list[3].deg')
-condicurrent=$(cat /tmp/current.json | jq -r '.weather[].description')
-condi2=$(cat /tmp/forecast.json | jq -r '.list[1].weather[].description')
-condi3=$(cat /tmp/forecast.json | jq -r '.list[2].weather[].description')
-condi4=$(cat /tmp/forecast.json | jq -r '.list[3].weather[].description')
+tempcurrent=$(jq -r '.main.temp' "/tmp/current.json")
+min2=$(jq -r '.list[1].temp.min' "/tmp/forecast.json")
+min3=$(jq -r '.list[2].temp.min' "/tmp/forecast.json")
+min4=$(jq -r '.list[3].temp.min' "/tmp/forecast.json")
+max2=$(jq -r '.list[1].temp.max' "/tmp/forecast.json")
+max3=$(jq -r '.list[2].temp.max' "/tmp/forecast.json")
+max4=$(jq -r '.list[3].temp.max' "/tmp/forecast.json")
+pressurecurrent=$(jq -r '.main.pressure' "/tmp/current.json")
+pressure2=$(jq -r '.list[1].pressure' "/tmp/forecast.json")
+pressure3=$(jq -r '.list[2].pressure' "/tmp/forecast.json")
+pressure4=$(jq -r '.list[3].pressure' "/tmp/forecast.json")
+humidcurrent=$(jq -r '.main.humidity' "/tmp/current.json")
+humid2=$(jq -r '.list[1].humidity' "/tmp/forecast.json")
+humid3=$(jq -r '.list[2].humidity' "/tmp/forecast.json")
+humid4=$(jq -r '.list[3].humidity' "/tmp/forecast.json")
+windcurrent=$(jq -r '.wind.speed' "/tmp/current.json")
+wind2=$(jq -r '.list[1].speed' "/tmp/forecast.json")
+wind3=$(jq -r '.list[2].speed' "/tmp/forecast.json")
+wind4=$(jq -r '.list[3].speed' "/tmp/forecast.json")
+direcurrent=$(jq -r '.wind.deg' "/tmp/current.json")
+dire2=$(jq -r '.list[1].deg' "/tmp/forecast.json")
+dire3=$(jq -r '.list[2].deg' "/tmp/forecast.json")
+dire4=$(jq -r '.list[3].deg' "/tmp/forecast.json")
+condicurrent=$(jq -r '.weather[].description' "/tmp/current.json")
+condi2=$(jq -r '.list[1].weather[].description' "/tmp/forecast.json")
+condi3=$(jq -r '.list[2].weather[].description' "/tmp/forecast.json")
+condi4=$(jq -r '.list[3].weather[].description' "/tmp/forecast.json")
 
-if [ "$uneet" == imperial ]
-then
-windcurrent1="$windcurrent"
-wind22="$wind2"
-wind33="$wind3"
-wind44="$wind4"
-symb=°F
-symb2=mph
+if [[ "$local_unit" == imperial ]]; then
+	windcurrent1="$windcurrent"
+	wind22="$wind2"
+	wind33="$wind3"
+	wind44="$wind4"
+	symb=$(echo -e "\u2109")
+	symb2="mph"
 else
-windcurrent1=$(perl -le 'print $ARGV[0] * 3.6' "$windcurrent")
-wind22=$(perl -le 'print $ARGV[0] * 3.6' "$wind2")
-wind33=$(perl -le 'print $ARGV[0] * 3.6' "$wind3")
-wind44=$(perl -le 'print $ARGV[0] * 3.6' "$wind4")
-symb=°C
-symb2=kph
+	windcurrent1=$(awk "BEGIN {print $windcurrent * 3.6}")
+	wind22=$(awk "BEGIN {print $wind2 * 3.6}")
+	wind33=$(awk "BEGIN {print $wind3 * 3.6}")
+	wind44=$(awk "BEGIN {print $wind4 * 3.6}")
+	symb=$(echo -e "\u2103")
+	symb2="kph"
 fi
 
-echo ""
+printf "\033c"
+
+echo -e '\e[01m'""
 echo -e "Location - $place, $nation:"
 echo ""
 echo -e "Current weather conditions:"
-echo ""
+echo -e '\e[0m'""
 echo -e "Temperature - $tempcurrent $symb"
 echo -e "Atmospheric Pressure - $pressurecurrent hPa"
 echo -e "Humidity - $humidcurrent %"
 echo -e "Wind speed - $windcurrent1 $symb2"
 echo -e "Wind direction - $direcurrent°"
 echo -e "Weather condition - $condicurrent"
-echo ""
-echo ""
+echo -e '\e[01m'""
 echo -e "Forecast for $time22:"
-echo ""
+echo -e '\e[0m'""
 echo -e "Minimum Temperature - $min2 $symb"
 echo -e "Maximum Temperature - $max2 $symb"
 echo -e "Atmospheric Pressure - $pressure2 hPa"
@@ -97,10 +167,9 @@ echo -e "Humidity - $humid2 %"
 echo -e "Wind speed - $wind22 $symb2"
 echo -e "Wind direction - $dire2°"
 echo -e "Weather condition - $condi2"
-echo ""
-echo ""
+echo -e '\e[01m'""
 echo -e "Forecast for $time33:"
-echo ""
+echo -e '\e[0m'""
 echo -e "Minimum Temperature - $min3 $symb"
 echo -e "Maximum Temperature - $max3 $symb"
 echo -e "Atmospheric Pressure - $pressure3 hPa"
@@ -108,10 +177,9 @@ echo -e "Humidity - $humid3 %"
 echo -e "Wind speed - $wind33 $symb2"
 echo -e "Wind direction - $dire3°"
 echo -e "Weather condition - $condi3"
-echo ""
-echo ""
+echo -e '\e[01m'""
 echo -e "Forecast for $time44:"
-echo ""
+echo -e '\e[0m'""
 echo -e "Minimum Temperature - $min4 $symb"
 echo -e "Maximum Temperature - $max4 $symb"
 echo -e "Atmospheric Pressure - $pressure4 hPa"
@@ -119,11 +187,10 @@ echo -e "Humidity - $humid4 %"
 echo -e "Wind speed - $wind44 $symb2"
 echo -e "Wind direction - $dire4°"
 echo -e "Weather condition - $condi4"
-echo ""
+echo -e ""
 
-rm /tmp/forecast.json
-rm /tmp/current.json
-
-fi
+"$local_rm" -f "/tmp/forecast.json"
+"$local_rm" -f "/tmp/current.json"
 
 exit 0
+########################################
